/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a username and password for a session.
         * @description Returns a short-lived access token in the body (the client keeps it in memory only)
         *     and sets a rotating refresh token in an httpOnly, SameSite=Strict cookie scoped to
         *     `/api/auth`.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh cookie and issue a new access token.
         * @description Each refresh token is single-use. Presenting one that was already used revokes every
         *     refresh token for that user (reuse detection), so a stolen token only works once.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the refresh token and clear the cookie. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the caller's tenant catalog.
         * @description Keyset pagination ordered by `title`, then `id`. `nextCursor` is opaque; pass it back
         *     unchanged to get the next page. It is `null` on the last page.
         */
        get: operations["searchCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one course, with a strong ETag. */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll the caller in a course. Idempotent per `Idempotency-Key`.
         * @description The client creates one `Idempotency-Key` per user intent and reuses it on retries.
         *     A repeat with the same key and body returns the original `201` response, with
         *     `Idempotency-Replayed: true`. The same key with a different body is a `422`.
         */
        post: operations["enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's enrollments, newest first. */
        get: operations["listMyEnrollments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an asynchronous report export. Managers only.
         * @description Returns `202 Accepted` at once, with the job and a `Location` header. Follow progress
         *     with `GET /jobs/{jobId}/events` (SSE) or by polling `GET /jobs/{jobId}`.
         */
        post: operations["requestReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll a job. */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent events for one job.
         * @description Each message is `event: job` with `data:` set to a `Job` snapshot as JSON, and `id:`
         *     set to an increasing sequence number. The first message is the current state. The
         *     server closes the stream after a `completed` or `failed` snapshot.
         *
         *     Browsers' `EventSource` can't send an `Authorization` header, so the web app reads
         *     this stream with `fetch` and parses it itself.
         */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a completed report as CSV. */
        get: operations["downloadJobResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Real-user monitoring beacon (web vitals and client errors).
         * @description Unauthenticated, because `navigator.sendBeacon` can't set headers. The BFF only logs
         *     these; production would forward them to an observability backend and rate-limit.
         */
        post: operations["reportRum"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem details. */
        Problem: {
            /** @description A URI that identifies the problem type, such as `/problems/already-enrolled`. */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description The trace this error belongs to, for support and log search. */
            traceId?: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        /** @enum {string} */
        Role: "learner" | "manager";
        User: {
            id: string;
            username: string;
            displayName: string;
            tenantId: string;
            tenantName: string;
            roles: components["schemas"]["Role"][];
        };
        Session: {
            accessToken: string;
            /** @description Seconds until the access token expires. */
            expiresIn: number;
            user: components["schemas"]["User"];
        };
        /** @enum {string} */
        CourseLevel: "beginner" | "intermediate" | "advanced";
        CourseSummary: {
            id: string;
            title: string;
            summary: string;
            level: components["schemas"]["CourseLevel"];
            durationMinutes: number;
        };
        Lesson: {
            id: string;
            title: string;
            durationMinutes: number;
        };
        Course: {
            id: string;
            title: string;
            summary: string;
            level: components["schemas"]["CourseLevel"];
            durationMinutes: number;
            description: string;
            lessons: components["schemas"]["Lesson"][];
            /** Format: date-time */
            updatedAt: string;
            /** @description Whether the caller is enrolled. */
            enrolled: boolean;
        };
        CoursePage: {
            items: components["schemas"]["CourseSummary"][];
            nextCursor: string | null;
        };
        EnrollmentRequest: {
            courseId: string;
        };
        Enrollment: {
            id: string;
            courseId: string;
            courseTitle: string;
            userId: string;
            /** @enum {string} */
            status: "active";
            /**
             * Format: date-time
             * @description UTC, with an explicit offset (`Z`).
             */
            enrolledAt: string;
        };
        EnrollmentList: {
            items: components["schemas"]["Enrollment"][];
        };
        ReportRequest: {
            /** @enum {string} */
            type: "completions";
            /**
             * @description Learning knob: the number of attempts the worker fails before it succeeds.
             *     1 or 2 shows a retry with backoff; 3 or more exhausts the retries and the job
             *     lands in the dead-letter list as `failed`.
             * @default 0
             */
            failAttempts: number;
        };
        /** @enum {string} */
        JobStatus: "queued" | "running" | "completed" | "failed";
        Job: {
            id: string;
            /** @enum {string} */
            type: "completions";
            status: components["schemas"]["JobStatus"];
            progress: number;
            /** @description The current or last attempt, starting at 1. 0 while queued. */
            attempt: number;
            maxAttempts: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Set when `status` is `completed`. */
            resultUrl: string | null;
            /** @description Set when `status` is `failed`. */
            error: string | null;
        };
        RumEvent: {
            /** @enum {string} */
            kind: "web-vital" | "error";
            /** @description `LCP`, `INP` or `CLS` for web vitals; the error name for errors. */
            name: string;
            value?: number;
            /** @enum {string} */
            rating?: "good" | "needs-improvement" | "poor";
            message?: string;
            url: string;
            traceId?: string;
        };
        RumBatch: {
            events: components["schemas"]["RumEvent"][];
        };
    };
    responses: {
        /** @description The request is malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, invalid or expired credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated, but not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource in the caller's tenant. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource's current state doesn't allow this. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Well-formed, but semantically invalid. */
        UnprocessableContent: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        CourseId: string;
        JobId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Strong validator for the representation. */
        ETag: string;
        /** @description URL of the created or accepted resource. */
        Location: string;
        /** @description `cw_refresh=<opaque>; Path=/api/auth; HttpOnly; SameSite=Strict` (plus `Secure` outside local dev). */
        RefreshCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["RefreshCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New session. */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["RefreshCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. Always succeeds, even without a cookie. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchCourses: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on the title. */
                q?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoursePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The course. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description Not modified since the ETag in `If-None-Match`. */
            304: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    enroll: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentRequest"];
            };
        };
        responses: {
            /** @description Enrolled (or a replay of the original enrollment). */
            201: {
                headers: {
                    /** @description Present, with the value `true`, when this is a replayed response. */
                    "Idempotency-Replayed"?: "true";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enrollment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableContent"];
        };
    };
    listMyEnrollments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's enrollments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    requestReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Accepted and queued. */
            202: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job's current state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream of `Job` snapshots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadJobResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    reportRum: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RumBatch"];
                /** @description The same JSON, as `sendBeacon` sends it when given a string. */
                "text/plain": string;
            };
        };
        responses: {
            /** @description Accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
}
